### ISSUE TITLE
error with spring boot

### ISSUE THREAD

**Issue by mapengfei00099** [aerospike/spring-data-aerospike#15]
erro info is :

Caused by: java.lang.ClassNotFoundException: org.springframework.data.querydsl.QueryDslUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]
	... 97 common frames omitted

**Comment by mzhangsfly** [comment]
looks like you are having trouble with spring boot.
