### ISSUE TITLE
Can not initialize AerospikePersistenceEntityIndexCreator in native graal

### ISSUE THREAD

**Issue by ijusti** [aerospike/spring-data-aerospike#696]
AerospikePersistenceEntityIndexCreator Can not be initialized in native graal

versions
```
<aerospike-client.version>7.2.1</aerospike-client.version>
<spring-data-aerospike.version>4.6.0</spring-data-aerospike.version>
<spring-boot-starter-data-aerospike.version>0.12.0</spring-boot-starter-data-aerospike.version>
graalVM 17.0.6
```

Stacktrace
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'aerospikeTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/aerospike/AerospikeDataConfiguration.class]: Unsatisfied dependency expressed through method 'aerospikeTemplate' parameter 2: Error creating bean with name 'mappingAerospikeConverter' defined in class path resource [org/springframework/boot/autoconfigure/data/aerospike/AerospikeCommonDataConfiguration.class]: Unsatisfied dependency expressed through method 'mappingAerospikeConverter' parameter 0: Error creating bean with name 'aerospikeMappingContext' defined in class path resource [org/springframework/boot/autoconfigure/data/aerospike/AerospikeCommonDataConfiguration.class]: Error creating bean with name 'aerospikePersistenceEntityIndexCreator' defined in class path resource [org/springframework/boot/autoconfigure/data/aerospike/AerospikeDataConfiguration.class]: Failed to instantiate [org.springframework.data.aerospike.index.AerospikePersistenceEntityIndexCreator]: Factory method 'aerospikePersistenceEntityIndexCreator' threw exception with message: 'void org.springframework.data.aerospike.index.AerospikePersistenceEntityIndexCreator.<init>(org.springframework.beans.factory.ObjectProvider, boolean, org.springframework.data.aerospike.index.AerospikeIndexResolver, org.springframework.data.aerospike.core.AerospikeTemplate)'
  at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797)
  at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1330)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:558)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:518)
  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
  at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:365)
  ... 127 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mappingAerospikeConverter' defined in class path resource [org/springframework/boot/autoconfigure/data/aerospike/AerospikeCommonDataConfiguration.class]: Unsatisfied dependency expressed through method 'mappingAerospikeConverter' parameter 0: Error creating bean with name 'aerospikeMappingContext' defined in class path resource [org/springframework/boot/autoconfigure/data/aerospike/AerospikeCommonDataConfiguration.class]: Error creating bean with name 'aerospikePersistenceEntityIndexCreator' defined in class path resource [org/springframework/boot/autoconfigure/data/aerospike/AerospikeDataConfiguration.class]: Failed to instantiate [org.springframework.data.aerospike.index.AerospikePersistenceEntityIndexCreator]: Factory method 'aerospikePersistenceEntityIndexCreator' threw exception with message: 'void org.springframework.data.aerospike.index.AerospikePersistenceEntityIndexCreator.<init>(org.springframework.beans.factory.ObjectProvider, boolean, org.springframework.data.aerospike.index.AerospikeIndexResolver, org.springframework.data.aerospike.core.AerospikeTemplate)'
  at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797)
  at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1330)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:558)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:518)
  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
  at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
  at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:906)
  at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:784)
  ... 137 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'aerospikeMappingContext' defined in class path resource [org/springframework/boot/autoconfigure/data/aerospike/AerospikeCommonDataConfiguration.class]: Error creating bean with name 'aerospikePersistenceEntityIndexCreator' defined in class path resource [org/springframework/boot/autoconfigure/data/aerospike/AerospikeDataConfiguration.class]: Failed to instantiate [org.springframework.data.aerospike.index.AerospikePersistenceEntityIndexCreator]: Factory method 'aerospikePersistenceEntityIndexCreator' threw exception with message: 'void org.springframework.data.aerospike.index.AerospikePersistenceEntityIndexCreator.<init>(org.springframework.beans.factory.ObjectProvider, boolean, org.springframework.data.aerospike.index.AerospikeIndexResolver, org.springframework.data.aerospike.core.AerospikeTemplate)'
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1768)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:596)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:518)
  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
  at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
  at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:906)
  at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:784)
  ... 151 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'aerospikePersistenceEntityIndexCreator' defined in class path resource [org/springframework/boot/autoconfigure/data/aerospike/AerospikeDataConfiguration.class]: Failed to instantiate [org.springframework.data.aerospike.index.AerospikePersistenceEntityIndexCreator]: Factory method 'aerospikePersistenceEntityIndexCreator' threw exception with message: 'void org.springframework.data.aerospike.index.AerospikePersistenceEntityIndexCreator.<init>(org.springframework.beans.factory.ObjectProvider, boolean, org.springframework.data.aerospike.index.AerospikeIndexResolver, org.springframework.data.aerospike.core.AerospikeTemplate)'
  at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
  at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1330)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:558)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:518)
  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
  at org.springframework.context.event.AbstractApplicationEventMulticaster.retrieveApplicationListeners(AbstractApplicationEventMulticaster.java:264)
  at org.springframework.context.event.AbstractApplicationEventMulticaster.getApplicationListeners(AbstractApplicationEventMulticaster.java:221)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:140)
  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:445)
  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
  at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:389)
  at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:339)
  at java.base/java.lang.Iterable.forEach(Iterable.java:75)
  at org.springframework.data.mapping.context.AbstractMappingContext.initialize(AbstractMappingContext.java:484)
  at org.springframework.data.mapping.context.AbstractMappingContext.afterPropertiesSet(AbstractMappingContext.java:476)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1815)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1764)
  ... 162 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.aerospike.index.AerospikePersistenceEntityIndexCreator]: Factory method 'aerospikePersistenceEntityIndexCreator' threw exception with message: 'void org.springframework.data.aerospike.index.AerospikePersistenceEntityIndexCreator.<init>(org.springframework.beans.factory.ObjectProvider, boolean, org.springframework.data.aerospike.index.AerospikeIndexResolver, org.springframework.data.aerospike.core.AerospikeTemplate)'
  at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
  at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:646)
  ... 183 more
Caused by: java.lang.NoSuchMethodError: 'void org.springframework.data.aerospike.index.AerospikePersistenceEntityIndexCreator.<init>(org.springframework.beans.factory.ObjectProvider, boolean, org.springframework.data.aerospike.index.AerospikeIndexResolver, org.springframework.data.aerospike.core.AerospikeTemplate)'
  at org.springframework.boot.autoconfigure.data.aerospike.AerospikeDataConfiguration.aerospikePersistenceEntityIndexCreator(AerospikeDataConfiguration.java:89)
  at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
  ... 184 more
```

**Comment by ijusti** [comment]
works for <spring-boot-starter-data-aerospike.version>0.13.0</spring-boot-starter-data-aerospike.version>
sorry for bothering
partial renovate
[compatibility table](https://github.com/aerospike-community/spring-data-aerospike-starters#versions-compatibility-table)
