### ISSUE TITLE
Getting java.lang.ClassNotFoundException: com.aerospike.client.BatchRecord exception

### ISSUE THREAD

**Issue by netizenp** [aerospike/spring-data-aerospike#709]
I'm using java 17 with spring data aerospike version as 4.6.0 and aerospike client version as 5.2.0.
Getting java.lang.ClassNotFoundException: com.aerospike.client.BatchRecord Exception

Not able to create aerospikeTemplate bean because of this.

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'aerospikeTemplateServiceImpl': Unsatisfied dependency expressed through field 'aerospikeTemplate': Error creating bean with name 'aerospikeTemplate' defined in class path resource [com/data/connector/testing/aerospike/config/AerospikeConfig.class]: Failed to instantiate [org.springframework.data.aerospike.core.AerospikeTemplate]: Factory method 'aerospikeTemplate' threw exception with message: com/aerospike/client/BatchRecord
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:787) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:767) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:508) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1419) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.3.jar:3.2.3]
	at com.data.connector.testing.aerospike.AerospikeTestingProj1Application.main(AerospikeTestingProj1Application.java:13) ~[classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'aerospikeTemplate' defined in class path resource [com/data/connector/testing/aerospike/config/AerospikeConfig.class]: Failed to instantiate [org.springframework.data.aerospike.core.AerospikeTemplate]: Factory method 'aerospikeTemplate' threw exception with message: com/aerospike/client/BatchRecord
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:485) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1335) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1165) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:784) ~[spring-beans-6.1.4.jar:6.1.4]
	... 20 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.aerospike.core.AerospikeTemplate]: Factory method 'aerospikeTemplate' threw exception with message: com/aerospike/client/BatchRecord
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:647) ~[spring-beans-6.1.4.jar:6.1.4]
	... 33 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/aerospike/client/BatchRecord
	at com.data.connector.testing.aerospike.config.AerospikeConfig.aerospikeTemplate(AerospikeConfig.java:22) ~[classes/:na]
	at com.data.connector.testing.aerospike.config.AerospikeConfig$$SpringCGLIB$$0.CGLIB$aerospikeTemplate$0(<generated>) ~[classes/:na]
	at com.data.connector.testing.aerospike.config.AerospikeConfig$$SpringCGLIB$$FastClass$$1.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.1.4.jar:6.1.4]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.1.4.jar:6.1.4]
	at com.data.connector.testing.aerospike.config.AerospikeConfig$$SpringCGLIB$$0.aerospikeTemplate(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140) ~[spring-beans-6.1.4.jar:6.1.4]
	... 34 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.aerospike.client.BatchRecord
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 45 common frames omitted`

**Comment by roimenashe** [comment]
Batch writes are supported since server version 6.0+ which means your Aerospike Java Client of 5.2.0 is too old (BatchRecord exists starting at 6.0.0 if i'm not mistaken).

Spring Data Aerospike 4.6.0 uses Aerospike Java Client of 7.2.0 behind the scenes.

I suggest to bump the Aerospike Java Client version to latest possible, if that's not an option check out the compatibility matrix of Spring Data Aerospike to see which version of Spring Data Aerospike you should use with your Aerospike Client version: https://github.com/aerospike/spring-data-aerospike?tab=readme-ov-file#spring-data-aerospike-compatibility

**Comment by netizenp** [comment]
Actually i'm looking to integrate my Aerospike jar (currently using aerospike client as 4.6.0 and spring data aerospike as ) with java 17 based application.

Now getting in creating a repository bean named as **ConsumedLimitRepository**

**Error**  Error creating bean with name 'consumedLimitRepository' defined in com.airtelbank.platform.data.connector.testing.aerospike.repository.ConsumedLimitRepository defined in @EnableAerospikeRepositories declared on AerospikeClientConfig: Cannot invoke "org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(java.lang.Class)" because "this.context" is null

In my Aerospike jar im defining **@EnableAerospikeRepositories(basePackages = {AerospikeClientConstant.BASE_PACKAGE,"${config.aerospike.repository.packages.scan}", "${config.aerospike.repository.packages.scan2}"})**
to enable aerospike repositories and provided the package of repository .

**Comment by netizenp** [comment]
Aerospike Bean definition : 

`@Bean
	public AerospikeTemplate aerospikeTemplate() {
		CustomConversions conversions = new CustomConversions(Arrays.asList(AerospikeClientConfigConvertor.StringToJava8LocalDateConverter.INSTANCE,
                AerospikeClientConfigConvertor.Java8LocalDateToStringConverter.INSTANCE,
                AerospikeClientConfigConvertor.ZonedDateTimeToStringConverter.INSTANCE,
                AerospikeClientConfigConvertor.StringToZonedDateTimeConverter.INSTANCE),
                AerospikeSimpleTypes.HOLDER);
		AerospikeMappingContext mappingContext = new AerospikeMappingContext();
		mappingContext.setDefaultNameSpace(aerospikeNamespace);
		MappingAerospikeConverter converter = new MappingAerospikeConverter(mappingContext,
                conversions, new AerospikeTypeAliasAccessor("type"));
		
		return new AerospikeTemplate(aerospikeClient(), aerospikeNamespace, converter, mappingContext, new DefaultAerospikeExceptionTranslator());
	}`


Repository : 
`@Repository
public interface ConsumedLimitRepository extends AerospikeRepository<ConsumedLimit, String>, KeyValueRepository<ConsumedLimit,String> {

}`


Facing error : 


org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'controller': Unsatisfied dependency expressed through field 'aerospikeJARService': Error creating bean with name 'aerospikeJARService': Unsatisfied dependency expressed through field 'consumedLimitDao': Error creating bean with name 'consumedLimitDaoImpl': Unsatisfied dependency expressed through field 'consumedLimitRepository': Error creating bean with name 'consumedLimitRepository' defined in com.data.connector.testing.aerospike.repository.ConsumedLimitRepository defined in @EnableAerospikeRepositories declared on AerospikeClientConfig: Cannot resolve reference to bean 'aerospikeTemplate' while setting bean property 'operations'

**Comment by agrgr** [comment]
Hey @netizenp,
Can you please provide a sample of your project rather than copying parts of code? Ideally as Github repo.
It would be much easier to get the structure, see the beans and understand the cause, and it will save time as well.
For instance, it is not clear why do you create a new instance of CustomConversions inside AerospikeTemplate bean.

Other than that, if the version of Spring Data Aerospike is 2.0.1.RELEASE (and not 4.6.0 as written in the very first line), it is quite old, and the amount of changes since then might make it unachievable to combine with the newer versions of other dependencies. As Roi has mentioned, please take a look at the compatibility matrix.

Thanks!

**Comment by netizenp** [comment]
Cool. now I'm using spring data aerospike 3.5.0 and its working fine from spring boot version 2.3.0.RELEASE till 3.2.3. 

Thanks
